routes/web.php
<?php

use Illuminate\Support\Facades\App;
use App\Models\Admin\Pages\Contents;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
*/

// ---------------------------------------------------------------------------------------------

// Web

Route::get('', function () {
    return view('base');
});

// ---------------------------------------------------------------------------------------------

// Blog

Route::group(['prefix' => 'blog', 'as' => 'blog.'], function () {
    Route::get('/', ['as' => 'index', 'uses' => 'Blog\BlogController@index']);
    Route::get('/post/{title}/{id}', ['as' => 'post', 'uses' => 'Blog\PostController@index'])->where('id', '[0-9]+');
    Route::post('/comment/{title}/{id}', ['as' => 'comment', 'uses' => 'Blog\CommentController@index'])->where('id', '[0-9]+');
    Route::get('/categorie/{title}/{id}', ['as' => 'categorie', 'uses' => 'Blog\CategorieController@index'])->where('id', '[0-9]+');
    Route::get('/search', ['as' => 'search', 'uses' => 'Blog\SearchController@index']);
    Route::get('/sitemap.xml', ['as' => 'sitemap', 'uses' => 'Blog\SitemapController@index']);
});

// ---------------------------------------------------------------------------------------------

// Mobule: AUTH

Route::group(['as' => 'auth.'], function () {
    Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');
    Route::post('login', ['as' => 'login', 'uses' => 'Auth\LoginController@login']);
    Route::get('logout', ['as' => 'logout', 'uses' => 'Auth\LogoutController@logout']);

    Route::get('password/email', ['as' => 'password.forgot', 'uses' => 'Auth\ForgotPasswordController@showLinkRequestForm']);
    Route::post('password/email', ['as' => 'password.send', 'uses' => 'Auth\ForgotPasswordController@sendResetLinkEmail']);
    Route::get('password/reset/{token?}', ['as' => 'password.reset', 'uses' => 'Auth\ResetPasswordController@showResetForm']);
    Route::post('password/reset', ['as' => 'password.reset', 'uses' => 'Auth\ResetPasswordController@reset']);
});

// ---------------------------------------------------------------------------------------------

// Borgert CMS Admin

Route::group(['middleware' => 'auth', 'prefix' => 'admin', 'as' => 'admin.'], function () {

    // Dashboard
    Route::get('/', ['as' => 'index', 'uses' => 'Admin\DashboardController@index']);

    Route::get('logs', '\Rap2hpoutre\LaravelLogViewer\LogViewerController@index')->name('logs.index');

    // ---------------------------------------------------------------------------------------------

    // Mobule: BLOG

    Route::group(['prefix' => 'blog', 'as' => 'blog.'], function () {

        // Categorys
        Route::resource('categorys', 'Admin\Blog\CategorysController');
        Route::post('categorys/update/{id}', 'Admin\Blog\CategorysController@update')->name('categorys.update');
        Route::post('categorys/destroy', 'Admin\Blog\CategorysController@destroy')->name('categorys.destroy');

        // Posts
        Route::resource('posts', 'Admin\Blog\PostsController');
        Route::post('posts/update/{id}', 'Admin\Blog\PostsController@update')->name('posts.update');
        Route::post('posts/destroy', 'Admin\Blog\PostsController@destroy')->name('posts.destroy');
        Route::any('posts/upload/{id?}', 'Admin\Blog\PostsController@upload')->name('posts.upload');

        // Comments
        Route::group(['prefix' => 'comments', 'as' => 'comments.'], function () {
            Route::get('index', ['as' => 'index', 'uses' => 'Admin\Blog\CommentsController@index']);
            Route::get('aproved', ['as' => 'aproved', 'uses' => 'Admin\Blog\CommentsController@aproved']);
            Route::get('reproved', ['as' => 'reproved', 'uses' => 'Admin\Blog\CommentsController@reproved']);
            Route::get('aprove/{id}', ['as' => 'aprove', 'uses' => 'Admin\Blog\CommentsController@aprove']);
            Route::get('reprove/{id}', ['as' => 'reprove', 'uses' => 'Admin\Blog\CommentsController@reprove']);
        });
    });

    // ---------------------------------------------------------------------------------------------

    // Mobule: GALLERYS

    Route::resource('gallerys', 'Admin\Gallerys\GallerysController');
    Route::post('gallerys/destroy', 'Admin\Gallerys\GallerysController@destroy')->name('gallerys.destroy');
    Route::post('gallerys/update/{id}', 'Admin\Gallerys\GallerysController@update')->name('gallerys.update');
    Route::any('gallerys/upload/{id?}', 'Admin\Gallerys\GallerysController@upload')->name('gallerys.upload');

    // ---------------------------------------------------------------------------------------------

    // Mobule: MAILBOX

    Route::group(['prefix' => 'mailbox', 'as' => 'mailbox.'], function () {
        Route::get('inbox', ['as' => 'inbox', 'uses' => 'Admin\Mailbox\InboxController@index']);
        Route::get('trash', ['as' => 'trash', 'uses' => 'Admin\Mailbox\TrashController@index']);
        Route::post('trash/{id}', ['as' => 'trash_in', 'uses' => 'Admin\Mailbox\TrashController@trash'])->where('id', '[0-9]+');
        Route::get('archive', ['as' => 'archive', 'uses' => 'Admin\Mailbox\ArchiveController@index']);
        Route::post('archive/{id}', ['as' => 'archive_in', 'uses' => 'Admin\Mailbox\ArchiveController@archive'])->where('id', '[0-9]+');
        Route::get('message/{id}', ['as' => 'message', 'uses' => 'Admin\Mailbox\MessageController@index'])->where('id', '[0-9]+');
        Route::post('delete', ['as' => 'delete', 'uses' => 'Admin\Mailbox\DeleteController@destroy']);
    });

    // ---------------------------------------------------------------------------------------------

    // Mobule: PAGES

    Route::group(['prefix' => 'pages', 'as' => 'pages.'], function () {

        // Categorys
        Route::resource('categorys', 'Admin\Pages\CategorysController');
        Route::post('categorys/update/{id}', 'Admin\Pages\CategorysController@update')->name('categorys.update');
        Route::post('categorys/destroy', 'Admin\Pages\CategorysController@destroy')->name('categorys.destroy');

        // Contents
        Route::resource('contents', 'Admin\Pages\ContentsController');
        Route::post('contents/update/{id}', 'Admin\Pages\ContentsController@update')->name('contents.update');
        Route::post('contents/destroy', 'Admin\Pages\ContentsController@destroy')->name('contents.destroy');
    });

    // ---------------------------------------------------------------------------------------------

    // Mobule: PRODUCTS

    Route::group(['prefix' => 'products', 'as' => 'products.'], function () {

        // Categorys
        Route::resource('categorys', 'Admin\Products\CategorysController');
        Route::post('categorys/update/{id}', 'Admin\Products\CategorysController@update')->name('categorys.update');
        Route::post('categorys/destroy', 'Admin\Products\CategorysController@destroy')->name('categorys.destroy');

        // Contents
        Route::resource('contents', 'Admin\Products\ContentsController');
        Route::post('contents/update/{id}', 'Admin\Products\ContentsController@update')->name('contents.update');
        Route::post('contents/destroy', 'Admin\Products\ContentsController@destroy')->name('contents.destroy');
        Route::any('contents/upload/{id?}', 'Admin\Products\ContentsController@upload')->name('contents.upload');
    });

    // ---------------------------------------------------------------------------------------------

    // Mobule: PROFILE

    Route::group(['prefix' => 'profile', 'as' => 'profile.'], function () {
        Route::get('', ['as' => 'profile', 'uses' => 'Admin\Profile\ProfileController@index']);
        Route::post('update', ['as' => 'update', 'uses' => 'Admin\Profile\ProfileController@password']);
    });

    // ---------------------------------------------------------------------------------------------

    // Mobule: USERS

    Route::resource('users', 'Admin\Users\UsersController');
    Route::post('users/update/{id}', 'Admin\Users\UsersController@update')->name('users.update');
    Route::post('users/destroy', 'Admin\Users\UsersController@destroy')->name('users.destroy');
});

// ---------------------------------------------------------------------------------------------

// Custom pages model

Route::get('/{page}', ['as' => 'pages', function ($page) {
    $page = Contents::where('slug', $page)->first();
    if (isset($page)) {
        return view('site.pages.template', ['page' => $page]);
    }

    App::abort(404);
}]);

// ---------------------------------------------------------------------------------------------

app/Models/Admin/Blog/Categorys.php
<?php

namespace App\Models\Admin\Blog;

use Kyslik\ColumnSortable\Sortable;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Categorys extends Model
{
    use SoftDeletes, Sortable;

    protected $table = 'blog_category';

    protected $fillable = [
        'title',
        'order',
        'status',
    ];

    protected $sortable = [
        'id',
        'title',
        'order',
        'status',
        'created_at',
    ];

    // ----------------------------------------------------------------------------

    public function seo($type = null)
    {
        if ($type === null) {
            return;
        }

        if ($type === 'title') {
            if (! empty($this->seo_title)) {
                return str_limit($this->seo_title, 70);
            }

            return str_limit($this->title, 70);
        }

        if ($type === 'description') {
            if (! empty($this->seo_description)) {
                return str_limit($this->seo_description, 170);
            }

            return str_limit($this->summary, 170);
        }

        if ($type === 'keywords') {
            return $this->seo_keywords;
        }
    }

    // ----------------------------------------------------------------------------
}

app/Models/Admin/Pages/Categorys.php
<?php

namespace App\Models\Admin\Pages;

use Kyslik\ColumnSortable\Sortable;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Categorys extends Model
{
    use SoftDeletes, Sortable;

    protected $table = 'pages_categorys';

    protected $fillable = [
        'title',
        'status',
        'order',
    ];

    protected $sortable = [
        'id',
        'title',
        'order',
        'status',
        'created_at',
    ];
}

app/Http/Controllers/Admin/Blog/CategorysController.php
<?php

namespace App\Http\Controllers\Admin\Blog;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Models\Admin\Blog\Categorys;

class CategorysController extends Controller
{
    /**
     * @var Categorys
     */
    protected $categorys;

    /**
     * CategorysController constructor.
     * @param Categorys $categorys
     */
    public function __construct(Categorys $categorys)
    {
        $this->categorys = $categorys;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $categorys = $this->categorys->sortable(['created_at' => 'desc'])->paginate(10);

        return view('admin.blog.categorys.index', ['categorys' => $categorys]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.blog.categorys.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     *
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'title' => 'required',
        ]);

        $categoryDetails = $request->all();
        $categoryDetails['status'] = isset($request->status) ? 1 : 0;
        $this->categorys->create($categoryDetails);

        \Session::flash('success', trans('admin/blog.categorys.store.messages.success'));

        return redirect()->route('admin.blog.categorys.index')->withInput();
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param int $id
     *
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $category = $this->categorys->find($id);

        return view('admin.blog.categorys.edit', ['category' => $category]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param int                      $id
     *
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request)
    {
        $this->validate($request, [
            'title' => 'required',
        ]);

        $category = $this->categorys->find($request->id);

        $categoryDetails = $request->all();
        $categoryDetails['status'] = isset($request->status) ? 1 : 0;
        $category->update($categoryDetails);

        \Session::flash('success', trans('admin/blog.categorys.update.messages.success'));

        return redirect()->route('admin.blog.categorys.index')->withInput();
    }

    /**
     * Remove the specified resource from storage.
     *
     * @return \Illuminate\Http\Response
     */
    public function destroy(Request $request)
    {
        if (is_null($request->categorys)) {
            \Session::flash('info', trans('admin/blog.categorys.destroy.messages.info'));

            return redirect()->route('admin.blog.categorys.index');
        }

        $this->categorys->destroy($request->categorys);
        \Session::flash('success', trans('admin/blog.categorys.destroy.messages.success'));

        return redirect()->route('admin.blog.categorys.index');
    }
}

app/Http/Controllers/Admin/Pages/CategorysController.php
<?php

namespace App\Http\Controllers\Admin\Pages;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Models\Admin\Pages\Categorys;

class CategorysController extends Controller
{
    /**
     * @var Categorys
     */
    protected $categorys;

    /**
     * CategorysController constructor.
     * @param Categorys $categorys
     */
    public function __construct(Categorys $categorys)
    {
        $this->categorys = $categorys;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $categorys = $this->categorys->sortable(['created_at' => 'desc'])->paginate(10);

        return view('admin.pages.categorys.index', ['categorys' => $categorys]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.pages.categorys.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     *
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'title' => 'required',
        ]);

        $categoryDetail = $request->all();
        $categoryDetail['status'] = isset($request->status) ? 1 : 0;
        $this->categorys->create($categoryDetail);

        \Session::flash('success', trans('admin/pages.categorys.store.messages.success'));

        return redirect()->route('admin.pages.categorys.index')->withInput();
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param int $id
     *
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $category = Categorys::find($id);

        return view('admin.pages.categorys.edit', ['category' => $category]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param int                      $id
     *
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request, [
            'title' => 'required',
        ]);

        $category = $this->categorys->find($id);

        $categoryDetail = $request->all();
        $categoryDetail['status'] = isset($request->status) ? 1 : 0;
        $category->update($categoryDetail);

        \Session::flash('success', trans('admin/pages.categorys.update.messages.success'));

        return redirect()->route('admin.pages.categorys.index')->withInput();
    }

    /**
     * Remove the specified resource from storage.
     *
     * @return \Illuminate\Http\Response
     */
    public function destroy(Request $request)
    {
        if (is_null($request->categorys)) {
            \Session::flash('info', trans('admin/pages.categorys.destroy.messages.info'));

            return redirect()->route('admin.pages.categorys.index');
        }

        Categorys::destroy($request->categorys);
        \Session::flash('success', trans('admin/pages.categorys.destroy.messages.success'));

        return redirect()->route('admin.pages.categorys.index');
    }
}

resources/views/admin/products/categorys/create.blade.php
@extends('admin.products.base')

@section('title',  trans('admin/products.categorys.create.title'), @parent)

@section('actions')
    <a href="{{ route('admin.products.categorys.index') }}" class="btn btn-default"><i class="fa fa-angle-left"></i> @lang('admin/_globals.buttons.back')</a>
@endsection

@section('products')
	
	@section('subtitle',  trans('admin/products.categorys.create.title'))

	<div class="tabs-container">

        <ul class="nav nav-tabs">
            <li><a class="nav-link active" data-toggle="tab" href="#tab-contents"> @lang('admin/_globals.forms.nav.contents')</a></li>
        </ul>

        <form action="{{ route('admin.products.categorys.store') }}" method="post">
            <div class="tab-content">

                <div id="tab-contents" class="tab-pane active">
                    <div class="panel-body">
                        {{ csrf_field() }}
                        <div class="form-group">
                            <label>@lang('admin/_globals.forms.category'):</label>
                            <input type="text" name="title" class="form-control" value="{{ old('title') }}">
                        </div>
                        <div class="form-group">
                            <label>@lang('admin/_globals.forms.order'):</label>
                            <input type="number" min="0" name="order" class="form-control" value="{{ old('order') }}">
                        </div>
                        <div class="form-group">
                            <label>@lang('admin/_globals.forms.status'):</label>
                            <input type="checkbox" name="status" class="js-switch" value="1" {{ old('status') === 1 ? 'checked' : '' }} />
                        </div>
                        <div class="form-group">
                            <button type="submit" class="btn btn-primary"><i class="fa fa-check"></i> @lang('admin/_globals.buttons.create')</button>
                        </div>
                    </div>
                </div>

            </div>
        </form>
        
	</div>

@endsection

resources/views/admin/products/categorys/edit.blade.php
@extends('admin.products.base')

@section('title',  trans('admin/products.categorys.edit.title'), @parent)

@section('actions')
	<a href="{{ route('admin.products.categorys.index') }}" class="btn btn-default"><i class="fa fa-angle-left"></i> @lang('admin/_globals.buttons.back')</a>
@endsection

@section('products')
	
	@section('subtitle',  trans('admin/products.categorys.edit.title'))

	<div class="tabs-container">

        <ul class="nav nav-tabs">
            <li><a class="nav-link active" data-toggle="tab" href="#tab-contents"> @lang('admin/_globals.forms.nav.contents')</a></li>
        </ul>

        <form action="{{ route('admin.products.categorys.update',$category->id) }}" method="post">
            <div class="tab-content">
                <div id="tab-contents" class="tab-pane active">
                    <div class="panel-body">
                        {{ csrf_field() }}
                        <div class="form-group">
                            <label>@lang('admin/_globals.forms.category'):</label>
                            <input type="text" name="title" class="form-control" value="{{ $category->title }}">
                        </div>
                        <div class="form-group">
                            <label>@lang('admin/_globals.forms.order'):</label>
                            <input type="number" min="0" name="order" class="form-control" value="{{ $category->order }}">
                        </div>
                        <div class="form-group">
                            <label>@lang('admin/_globals.forms.status'):</label>
                            <input type="checkbox" name="status" class="js-switch" value="1" {{ $category->status === 1 ? 'checked' : '' }} />
                        </div>
                        <div class="form-group">
                            <button type="submit" class="btn btn-primary"><i class="fa fa-check"></i> @lang('admin/_globals.buttons.save')</button>
                        </div>
                    </div>
                </div>
            </div>
        </form>

	</div>

@endsection

resources/views/admin/products/categorys/index.blade.php
@extends('admin.products.base')

@section('title', trans('admin/products.categorys.index.title', ['total' => $categorys->total()]), @parent)

@section('actions')
	<a href="{{ route('admin.products.categorys.create') }}" class="btn dim btn-primary"><i class="fa fa-plus"></i> @lang('admin/_globals.buttons.create')</a>
@endsection

@section('products')
	
	@section('subtitle', trans('admin/products.categorys.index.title', ['total' => $categorys->total()]))

    @if ($categorys->total() > 0)
        <form action="{{ route('admin.products.categorys.destroy') }}" method="post">
            {{ csrf_field() }}
            <div class="table-responsive">
                <table class="table table-striped table-align-middle">
                    <thead>
                        <tr>
                            <th>@sortablelink('id', '#')</th>
                            <th>@sortablelink('created_at', trans('admin/_globals.tables.created_at'))</th>
                            <th>@sortablelink('title', trans('admin/_globals.tables.title'))</th>
                            <th>@sortablelink('order', trans('admin/_globals.tables.order'))</th>
                            <th>@sortablelink('status', trans('admin/_globals.tables.status'))</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach($categorys as $key => $category)
                            <tr>
                                <td><input type="checkbox" class="i-checks" name="categorys[]" value="{{ $category->id }}"></td>
                                <td>{{ $category->created_at->diffForHumans()  }}</td>
                                <td>{{ $category->title }}</td>
                                <td>{{ $category->order }}</td>
                                <td>
                                    @if ($category->status === 1)
                                        <span class="badge badge-success">@lang('admin/_globals.tables.active')</span>
                                    @elseif ($category->status === 0)
                                        <span class="badge badge-secondary">@lang('admin/_globals.tables.inactive')</span>
                                    @endif
                                </td>
                                <td class="text-right">
                                    <a href="{{ route('admin.products.categorys.edit',$category->id) }}" class="btn btn-primary">@lang('admin/_globals.buttons.edit')</a>
                                </td>
                            </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>
            <button type="submit" class="btn btn-danger"><i class="fa fa-trash"></i> @lang('admin/_globals.buttons.delete_selected')</button>
        </form>
        {!! $categorys->render() !!}
    @else
        <div class="text-center">
            <i class="fa fa-exclamation-triangle fa-2x"></i>
            <p>@lang('admin/products.categorys.index.is_empty')</p>
        </div>
    @endif

@endsection